# .scrutinizer.yml

checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    php: '7.0.8'
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=.selami_coverage'
        coverage:
          file: '.selami_coverage'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"