language: php

sudo: false

php:
  - 7.1
  - 7.0


before_script:
  - pecl channel-update pecl.php.net
  - pecl install yaml-2.0.0 < /dev/null
  - echo "extension = yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install -n

addons:
  apt:
    packages:
      - libyaml-dev
script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ $TRAVIS_PHP_VERSION >= '7.0' ]; then php vendor/bin/coveralls; fi

after_success:
  - travis_retry php vendor/bin/coveralls -v